import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="flex h-screen justify-center items-center text-3xl text-red-500/70">
        Next JS + Tailwind CSS
      </h1>
    </div>
  );
}
